### ISSUE TITLE
Entering the restore point

### ISSUE THREAD

**Issue by archem245** [yetanothermightytool/powershell#3]
I am unable to select the restore point.  It appears you have a not condition that needs removed on line 127 column 12. Removing that Exclamation point allow me to select the restore point.

**Comment by yetanothermightytool** [comment]
Hello @archem245: Can you tell me which script you are referring to?

**Comment by archem245** [comment]
Sorry for not being specific.  I was referring to vbr-securerestore.ps1

**Comment by yetanothermightytool** [comment]
@archem245: Got it. Please share details about your setup, specifically the PowerShell version, so I can recreate the issue. 
I will improve this part of the code asap.
Thanks.

**Comment by yetanothermightytool** [comment]
@archem245: Updated both vbr-securerestore.ps1 scripts (also the one in v12.1 folder). This update will be documented in the README for the next version, as I'm currently testing all scripts in the latest Veeam Backup & Replication version 12.2
Thanks for bringing this up.
